// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The Kodela Authors
/**
 * Sprint 3 / [E.14] — `kodela export-graph` command.
 *
 * Exports the in-memory context graph (files + functions + context annotations,
 * with contains/dependency/reference edges) in three formats agents and humans
 * can pipe into other tools:
 *
 *   - `json`     — the SerializedGraph shape from @kodela/core verbatim.
 *                  Useful for Obsidian Graph plugin imports + external tools.
 *   - `mermaid`  — a flowchart in Mermaid syntax, ready to paste into any
 *                  Markdown viewer that renders Mermaid (Obsidian, GitHub,
 *                  Notion, MkDocs).  Edges are labelled by kind.
 *   - `obsidian` — a Markdown index page with `[[wiki-links]]` for every file
 *                  + function, grouped by file, with bullet-list edges.
 *                  Drop into an Obsidian vault and the graph appears.
 *
 * The persisted code-graph today has NO call edges — only contains (file→fn,
 * fn→context), dependency (file→file imports), and reference (context→fn)
 * edges.  The Mermaid output therefore renders the structural graph, not a
 * call-flow.  Once call-edge extraction lands (separate ticket), the Mermaid
 * renderer can branch on edge kind to emit `-->` for calls.
 */

import path from "node:path";
import { buildGraph, serializeGraph } from "@kodela/core";
import type {
  GraphNode,
  GraphEdge,
  SerializedGraph,
} from "@kodela/core";

export type ExportGraphFormat = "json" | "mermaid" | "obsidian";

export type ExportGraphOptions = {
  repoRoot: string;
  format: ExportGraphFormat;
  /** When set, only emit nodes/edges that touch this file (or descendants). */
  scopeFile?: string;
};

export type ExportGraphResult = {
  format: ExportGraphFormat;
  content: string;
  /** Number of nodes that survived the scope filter (informational, not the graph total). */
  nodeCount: number;
  edgeCount: number;
};

export async function runExportGraph(
  opts: ExportGraphOptions,
): Promise<ExportGraphResult> {
  const graph = await buildGraph(opts.repoRoot);
  const serialized = serializeGraph(graph);

  const scoped = opts.scopeFile
    ? filterByScope(serialized, opts.scopeFile)
    : serialized;

  let content: string;
  switch (opts.format) {
    case "json":
      content = JSON.stringify(scoped, null, 2);
      break;
    case "mermaid":
      content = renderMermaid(scoped);
      break;
    case "obsidian":
      content = renderObsidian(scoped);
      break;
  }

  return {
    format: opts.format,
    content,
    nodeCount: scoped.nodes.length,
    edgeCount: scoped.edges.length,
  };
}

function filterByScope(
  graph: SerializedGraph,
  scopeFile: string,
): SerializedGraph {
  const norm = scopeFile.replace(/\\/g, "/");
  const keptIds = new Set<string>();
  for (const node of graph.nodes) {
    if (node.kind === "file" && (node.path === norm || node.path.startsWith(norm + "/"))) {
      keptIds.add(node.id);
    } else if (
      (node.kind === "function" || node.kind === "context") &&
      (node.filePath === norm || node.filePath.startsWith(norm + "/"))
    ) {
      keptIds.add(node.id);
    }
  }
  const nodes = graph.nodes.filter((n) => keptIds.has(n.id));
  const edges = graph.edges.filter((e) => keptIds.has(e.from) && keptIds.has(e.to));
  return {
    nodes,
    edges,
    summary: {
      fileCount: nodes.filter((n) => n.kind === "file").length,
      functionCount: nodes.filter((n) => n.kind === "function").length,
      contextCount: nodes.filter((n) => n.kind === "context").length,
      dependencyEdgeCount: edges.filter((e) => e.kind === "dependency").length,
      containsEdgeCount: edges.filter((e) => e.kind === "contains").length,
      referenceEdgeCount: edges.filter((e) => e.kind === "reference").length,
    },
  };
}

function mermaidNodeId(rawId: string): string {
  // Mermaid IDs must be alphanumeric + underscore; anything else becomes "_".
  return "n_" + rawId.replace(/[^A-Za-z0-9_]/g, "_");
}

function mermaidLabel(node: GraphNode): string {
  if (node.kind === "file") return path.basename(node.path);
  if (node.kind === "function") return `${node.name}()`;
  return `note L${node.lineRange.start}`;
}

function renderMermaid(graph: SerializedGraph): string {
  const lines: string[] = [
    "flowchart LR",
    "  %% Generated by kodela export-graph",
    `  %% nodes=${graph.nodes.length} edges=${graph.edges.length}`,
  ];

  for (const node of graph.nodes) {
    const id = mermaidNodeId(node.id);
    const label = mermaidLabel(node).replace(/"/g, "'");
    const shape =
      node.kind === "file" ? `[(${label})]` :
      node.kind === "function" ? `["${label}"]` :
      `{{${label}}}`;
    lines.push(`  ${id}${shape}`);
  }

  for (const edge of graph.edges) {
    const arrow = edgeArrow(edge);
    lines.push(
      `  ${mermaidNodeId(edge.from)} ${arrow} ${mermaidNodeId(edge.to)}`,
    );
  }

  return lines.join("\n") + "\n";
}

function edgeArrow(edge: GraphEdge): string {
  switch (edge.kind) {
    case "contains":
      return "-->|contains|";
    case "dependency":
      return "-.->|imports|";
    case "reference":
      return "==>|annotated|";
  }
}

function renderObsidian(graph: SerializedGraph): string {
  const fileNodes = graph.nodes.filter((n): n is Extract<GraphNode, { kind: "file" }> => n.kind === "file");
  const functionsByFile = new Map<string, Extract<GraphNode, { kind: "function" }>[]>();
  const contextsByFile = new Map<string, Extract<GraphNode, { kind: "context" }>[]>();

  for (const node of graph.nodes) {
    if (node.kind === "function") {
      const list = functionsByFile.get(node.filePath) ?? [];
      list.push(node);
      functionsByFile.set(node.filePath, list);
    } else if (node.kind === "context") {
      const list = contextsByFile.get(node.filePath) ?? [];
      list.push(node);
      contextsByFile.set(node.filePath, list);
    }
  }

  const importsByFromPath = new Map<string, string[]>();
  for (const edge of graph.edges) {
    if (edge.kind !== "dependency") continue;
    const from = graph.nodes.find((n) => n.id === edge.from);
    const to = graph.nodes.find((n) => n.id === edge.to);
    if (from?.kind !== "file" || to?.kind !== "file") continue;
    const list = importsByFromPath.get(from.path) ?? [];
    list.push(to.path);
    importsByFromPath.set(from.path, list);
  }

  const lines: string[] = [
    "# Kodela Memory Graph",
    "",
    `> ${graph.summary.fileCount} files · ${graph.summary.functionCount} functions · ${graph.summary.contextCount} context annotations`,
    "",
    "Drop this Markdown file into an Obsidian vault — every `[[wiki-link]]` becomes a backlink, and the graph view auto-renders the structure.",
    "",
  ];

  for (const file of [...fileNodes].sort((a, b) => a.path.localeCompare(b.path))) {
    lines.push(`## [[${file.path}]]`);
    lines.push("");

    const fns = functionsByFile.get(file.path) ?? [];
    if (fns.length > 0) {
      lines.push("**Functions**");
      for (const fn of fns.sort((a, b) => a.name.localeCompare(b.name))) {
        lines.push(`- [[${file.path}#${fn.name}]] (${fn.astAnchor.kind})`);
      }
      lines.push("");
    }

    const ctxs = contextsByFile.get(file.path) ?? [];
    if (ctxs.length > 0) {
      lines.push("**Context annotations**");
      for (const ctx of ctxs.sort((a, b) => a.lineRange.start - b.lineRange.start)) {
        lines.push(
          `- L${ctx.lineRange.start}-${ctx.lineRange.end} · ${ctx.severity} · ${ctx.status}`,
        );
      }
      lines.push("");
    }

    const imports = importsByFromPath.get(file.path) ?? [];
    if (imports.length > 0) {
      lines.push("**Imports**");
      for (const imp of imports.sort()) {
        lines.push(`- [[${imp}]]`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}
