// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The Kodela Authors
/**
 * kodela memory-bank — auto-generate the agent "Memory Bank".
 *
 * The Memory Bank is a de-facto community standard (Cline / Roo / Cursor / etc.):
 * a `memory-bank/` folder of six markdown files that AI agents read at the start
 * of every task to rebuild project understanding after a context reset. Today
 * developers hand-write these files; Kodela generates and maintains them from
 * the context it already captures (project DNA + the *why* behind changes), so
 * the memory stays current for free.
 *
 *   kodela memory-bank            → write/refresh memory-bank/ (managed blocks only)
 *   kodela memory-bank --check    → exit 1 if the files are out of date (CI/hook)
 *   kodela memory-bank --dir docs/memory   → custom location
 *
 * Each file has a Kodela-managed block delimited by markers; anything a human
 * writes OUTSIDE the markers is preserved across regenerations.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { readDirectives, formatDirectivesBlock } from "@kodela/core/directives";
import { readAllEntries } from "./status.js";

export type MemoryBankOptions = {
  repoRoot: string;
  dir?: string;
  check?: boolean;
  output?: "text" | "json";
};

export type MemoryFileAction = "created" | "updated" | "unchanged";
export type MemoryFileResult = { file: string; action: MemoryFileAction };
export type MemoryBankResult = {
  dir: string;
  files: MemoryFileResult[];
  outdated: boolean;
  entryCount: number;
  check: boolean;
};

const BEGIN =
  "<!-- KODELA:AUTO BEGIN — generated by `kodela memory-bank`. Edits inside this block are overwritten; put your own notes BELOW the END marker. -->";
const END = "<!-- KODELA:AUTO END -->";

/** Minimal shape of .kodela/dna/project.json — all fields optional/defensive. */
interface Dna {
  project?: string;
  purpose?: string;
  stack?: string[];
  non_goals?: string[];
  key_constraints?: string[];
  technical?: {
    languages?: Record<string, number>;
    runtime?: Record<string, string>;
    build?: string;
    test?: string;
    architecture?: { pattern?: string; tiers?: string[] };
    data_stores?: string[];
  };
}

interface ContextLike {
  filePath: string;
  note: string;
  updatedAt: string;
  source?: string;
}

async function readJson<T>(file: string): Promise<T | null> {
  try {
    return JSON.parse(await fs.readFile(file, "utf8")) as T;
  } catch {
    return null;
  }
}

function fmtDate(iso: string): string {
  return iso.slice(0, 10);
}

function truncate(s: string, n: number): string {
  const flat = s.replace(/\s+/g, " ").trim();
  return flat.length > n ? flat.slice(0, n - 1) + "…" : flat;
}

/* ----------------------------------------------------------- file builders */

function projectBrief(dna: Dna | null, name: string, description: string): string {
  const lines = [`# Project Brief — ${name}`, ""];
  if (description) lines.push(`> ${description}`, "");
  lines.push("## What this is", dna?.purpose ?? description ?? "_No project DNA captured yet. Run `kodela connect` and let Kodela observe a few changes._", "");
  if (dna?.non_goals?.length) {
    lines.push("## Non-goals (explicitly out of scope)");
    for (const g of dna.non_goals) lines.push(`- ${g}`);
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}

function productContext(dna: Dna | null, description: string): string {
  const lines = ["# Product Context", "", "## Why this exists", dna?.purpose ?? description ?? "_Not yet captured._", ""];
  if (dna?.key_constraints?.length) {
    lines.push("## Constraints that shape it");
    for (const c of dna.key_constraints) lines.push(`- ${c}`);
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}

function activeContext(entries: ContextLike[]): string {
  const lines = ["# Active Context", "", `_${entries.length} captured change${entries.length === 1 ? "" : "s"} on record._`, ""];
  const recent = [...entries]
    .sort((a, b) => (b.updatedAt > a.updatedAt ? 1 : -1))
    .slice(0, 10);
  if (recent.length) {
    lines.push("## Recent changes — the *why*");
    for (const e of recent) {
      lines.push(`- \`${e.filePath}\` — ${truncate(e.note, 140)} _(${e.source ?? "?"}, ${fmtDate(e.updatedAt)})_`);
    }
    lines.push("");
  }
  // most-touched files
  const counts = new Map<string, number>();
  for (const e of entries) counts.set(e.filePath, (counts.get(e.filePath) ?? 0) + 1);
  const top = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8).filter(([, n]) => n > 1);
  if (top.length) {
    lines.push("## Most-documented areas");
    for (const [f, n] of top) lines.push(`- \`${f}\` — ${n} captured changes`);
    lines.push("");
  }
  if (!recent.length) {
    lines.push("_No context captured yet. As you work with AI tools, Kodela records the why and this file updates._", "");
  }
  return lines.join("\n").trimEnd();
}

function systemPatterns(dna: Dna | null): string {
  const a = dna?.technical?.architecture;
  const lines = ["# System Patterns", ""];
  lines.push("## Architecture", a?.pattern ?? "_Not yet captured._", "");
  if (a?.tiers?.length) {
    lines.push("### Tiers");
    for (const t of a.tiers) lines.push(`- ${t}`);
    lines.push("");
  }
  if (dna?.technical?.data_stores?.length) {
    lines.push("## Data stores");
    for (const d of dna.technical.data_stores) lines.push(`- ${d}`);
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}

function techContext(dna: Dna | null): string {
  const t = dna?.technical;
  const lines = ["# Tech Context", ""];
  if (dna?.stack?.length) {
    lines.push("## Stack");
    for (const s of dna.stack) lines.push(`- ${s}`);
    lines.push("");
  }
  if (t?.languages && Object.keys(t.languages).length) {
    const langs = Object.entries(t.languages)
      .sort((a, b) => b[1] - a[1])
      .map(([l, p]) => `${l} ${Math.round(p * 100)}%`)
      .join(" · ");
    lines.push("## Languages", langs, "");
  }
  const rt = t?.runtime ? Object.entries(t.runtime).map(([k, v]) => `${k} ${v}`).join(", ") : null;
  if (rt || t?.build || t?.test) {
    lines.push("## Toolchain");
    if (rt) lines.push(`- Runtime: ${rt}`);
    if (t?.build) lines.push(`- Build: ${t.build}`);
    if (t?.test) lines.push(`- Test: ${t.test}`);
    lines.push("");
  }
  if (!dna?.stack?.length && !t) lines.push("_Not yet captured._", "");
  return lines.join("\n").trimEnd();
}

function progress(entries: ContextLike[]): string {
  const files = new Set(entries.map((e) => e.filePath)).size;
  const bySource = new Map<string, number>();
  for (const e of entries) bySource.set(e.source ?? "?", (bySource.get(e.source ?? "?") ?? 0) + 1);
  const sources = [...bySource.entries()].map(([s, n]) => `${s}: ${n}`).join(", ") || "—";
  const lines = [
    "# Progress",
    "",
    "## What's captured",
    `- ${entries.length} context entr${entries.length === 1 ? "y" : "ies"} across ${files} file${files === 1 ? "" : "s"}`,
    `- By author — ${sources}`,
    "",
  ];
  return lines.join("\n").trimEnd();
}

const FOOTER = "\n\n_Maintained by Kodela — run `kodela memory-bank` to refresh._";

/* ----------------------------------------------------------------- merge */

/** Wrap generated content in the managed markers. */
function wrap(managed: string): string {
  return `${BEGIN}\n\n${managed}${FOOTER}\n\n${END}`;
}

/**
 * Merge a freshly-generated managed block into an existing file, preserving any
 * human-written content outside the markers. Returns the new content and what
 * action it represents.
 */
function merge(existing: string | null, managed: string): { content: string; action: MemoryFileAction } {
  const block = wrap(managed);
  if (existing == null) {
    return { content: block + "\n", action: "created" };
  }
  const re = new RegExp(`${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}`);
  if (re.test(existing)) {
    const next = existing.replace(re, block);
    return { content: next, action: next === existing ? "unchanged" : "updated" };
  }
  // File exists but isn't Kodela-managed yet — prepend the block, keep the rest.
  return { content: `${block}\n\n${existing.trimStart()}`, action: "updated" };
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/* --------------------------------------------------------------- runner */

/** Load DNA + entries and generate the managed (unwrapped) section content. */
async function generateSections(
  repoRoot: string,
): Promise<{ name: string; entryCount: number; generated: Record<string, string> }> {
  const dna = await readJson<Dna>(path.join(repoRoot, ".kodela", "dna", "project.json"));
  const pkg = await readJson<{ name?: string; description?: string }>(path.join(repoRoot, "package.json"));
  const entries = (await readAllEntries(repoRoot).catch(() => [])) as unknown as ContextLike[];
  // Phase 1 — standing directives lead activeContext so every agent that reads
  // the Memory Bank at task start honours them without being re-told.
  const directives = await readDirectives(repoRoot).catch(() => []);
  const directivesBlock = formatDirectivesBlock(directives);

  const name = pkg?.name ?? dna?.project ?? path.basename(repoRoot);
  const description = pkg?.description ?? "";

  return {
    name,
    entryCount: entries.length,
    generated: {
      "projectbrief.md": projectBrief(dna, name, description),
      "productContext.md": productContext(dna, description),
      "activeContext.md": (directivesBlock ? `${directivesBlock}\n` : "") + activeContext(entries),
      "systemPatterns.md": systemPatterns(dna),
      "techContext.md": techContext(dna),
      "progress.md": progress(entries),
    },
  };
}

/**
 * Render the Memory Bank files WITHOUT touching disk — the canonical content a
 * fresh `kodela memory-bank` would write (managed block wrapped in markers).
 * Used by the dashboard API so the in-app view matches the CLI output exactly.
 */
export async function renderMemoryBank(
  repoRoot: string,
): Promise<{ name: string; entryCount: number; files: { file: string; content: string }[] }> {
  const { name, entryCount, generated } = await generateSections(repoRoot);
  return {
    name,
    entryCount,
    files: Object.entries(generated).map(([file, managed]) => ({ file, content: wrap(managed) })),
  };
}

export async function runMemoryBank(opts: MemoryBankOptions): Promise<MemoryBankResult> {
  const { repoRoot } = opts;
  const dir = opts.dir ?? "memory-bank";
  const outDir = path.resolve(repoRoot, dir);

  const { entryCount, generated } = await generateSections(repoRoot);

  const files: MemoryFileResult[] = [];
  for (const [fileName, managed] of Object.entries(generated)) {
    const full = path.join(outDir, fileName);
    const existing = await fs.readFile(full, "utf8").catch(() => null);
    const { content, action } = merge(existing, managed);
    if (!opts.check && action !== "unchanged") {
      await fs.mkdir(outDir, { recursive: true });
      await fs.writeFile(full, content, "utf8");
    }
    files.push({ file: path.join(dir, fileName), action });
  }

  return {
    dir,
    files,
    outdated: files.some((f) => f.action !== "unchanged"),
    entryCount,
    check: !!opts.check,
  };
}

export function formatMemoryBankResult(
  result: MemoryBankResult,
  output: "text" | "json" = "text",
): string {
  if (output === "json") {
    return JSON.stringify(result, null, 2);
  }
  const lines: string[] = [];
  if (result.check) {
    if (result.outdated) {
      lines.push(`✗ Memory Bank is out of date in ${result.dir}/`);
      for (const f of result.files.filter((x) => x.action !== "unchanged")) {
        lines.push(`  • ${f.file} would be ${f.action}`);
      }
      lines.push(`→ run \`kodela memory-bank\` to refresh.`);
    } else {
      lines.push(`✓ Memory Bank is up to date (${result.dir}/).`);
    }
    return lines.join("\n");
  }
  const verb = (a: MemoryFileAction) => (a === "created" ? "✚ created" : a === "updated" ? "● updated" : "  unchanged");
  lines.push(`Memory Bank — ${result.dir}/  (${result.entryCount} captured change${result.entryCount === 1 ? "" : "s"})`);
  for (const f of result.files) lines.push(`  ${verb(f.action)}  ${f.file}`);
  const changed = result.files.filter((x) => x.action !== "unchanged").length;
  lines.push("");
  lines.push(
    changed === 0
      ? "Already up to date. Agents read these files at the start of every task."
      : `Done. Commit \`${result.dir}/\` so your team — and every AI agent — shares the same project memory.`,
  );
  return lines.join("\n");
}
