// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The Kodela Authors
/**
 * kodela pack — pack the repo + its captured *why* into one AI-ready file.
 *
 * Like Repomix, but with the reasoning: produces a single markdown artifact you
 * can paste into any LLM (or hand to an agent) containing the project DNA, a
 * repository map, and the captured context (the why behind changes). Works on a
 * cold repo — even with no captured context yet it emits the DNA + map.
 *
 *   kodela pack                  → write kodela-pack.md
 *   kodela pack --stdout         → print to stdout (pipe into pbcopy / an LLM)
 *   kodela pack --out ctx.md     → custom output path
 */
import fs from "node:fs/promises";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { readAllEntries } from "./status.js";

const execFileAsync = promisify(execFile);

export type PackOptions = {
  repoRoot: string;
  out?: string;
  stdout?: boolean;
  maxFiles?: number;
};

export type PackResult = {
  content: string;
  outPath?: string;
  fileCount: number;
  entryCount: number;
  bytes: number;
  tokenEstimate: number;
};

interface Dna {
  project?: string;
  purpose?: string;
  stack?: string[];
  non_goals?: string[];
  technical?: {
    architecture?: { pattern?: string; tiers?: string[] };
    data_stores?: string[];
  };
}

interface ContextLike {
  filePath: string;
  note: string;
  updatedAt: string;
  source?: string;
  severity?: string;
}

async function readJson<T>(file: string): Promise<T | null> {
  try {
    return JSON.parse(await fs.readFile(file, "utf8")) as T;
  } catch {
    return null;
  }
}

async function gitFiles(repoRoot: string, cap: number): Promise<string[]> {
  try {
    const { stdout } = await execFileAsync("git", ["ls-files"], {
      cwd: repoRoot,
      maxBuffer: 16 * 1024 * 1024,
    });
    return stdout.split("\n").filter(Boolean).slice(0, cap);
  } catch {
    return [];
  }
}

/** Group files by top-level directory for a compact map. */
function buildMap(files: string[]): string {
  const groups = new Map<string, number>();
  for (const f of files) {
    const top = f.includes("/") ? f.slice(0, f.indexOf("/")) + "/" : f;
    groups.set(top, (groups.get(top) ?? 0) + 1);
  }
  const lines = [...groups.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([dir, n]) => (dir.endsWith("/") ? `- \`${dir}\` — ${n} files` : `- \`${dir}\``));
  return lines.join("\n");
}

export async function runPack(opts: PackOptions): Promise<PackResult> {
  const { repoRoot } = opts;
  const cap = opts.maxFiles ?? 600;

  const dna = await readJson<Dna>(path.join(repoRoot, ".kodela", "dna", "project.json"));
  const pkg = await readJson<{ name?: string; description?: string }>(path.join(repoRoot, "package.json"));
  const entries = (await readAllEntries(repoRoot).catch(() => [])) as unknown as ContextLike[];
  const files = await gitFiles(repoRoot, cap);

  const name = pkg?.name ?? dna?.project ?? path.basename(repoRoot);

  const out: string[] = [];
  out.push(`# ${name} — Kodela pack`);
  out.push("");
  out.push(
    "> Generated by `kodela pack` — the repository plus the captured *why* behind its " +
      "changes, packed into one file for an AI agent. Paste this into your LLM.",
  );
  out.push("");

  // Project DNA
  if (dna?.purpose || dna?.stack?.length || dna?.technical) {
    out.push("## Project DNA");
    out.push("");
    if (dna.purpose) out.push(dna.purpose, "");
    if (dna.stack?.length) out.push(`**Stack:** ${dna.stack.join(" · ")}`, "");
    if (dna.technical?.architecture?.pattern)
      out.push(`**Architecture:** ${dna.technical.architecture.pattern}`, "");
    if (dna.technical?.data_stores?.length)
      out.push(`**Data stores:** ${dna.technical.data_stores.join("; ")}`, "");
    if (dna.non_goals?.length) {
      out.push("**Non-goals:**");
      for (const g of dna.non_goals) out.push(`- ${g}`);
      out.push("");
    }
  }

  // Repository map
  if (files.length) {
    out.push("## Repository map");
    out.push("");
    out.push(`_${files.length} tracked files${files.length >= cap ? " (capped)" : ""}._`);
    out.push("");
    out.push(buildMap(files));
    out.push("");
  }

  // Captured context — the why, grouped by file
  out.push("## Captured context — the *why* behind changes");
  out.push("");
  if (entries.length) {
    const byFile = new Map<string, ContextLike[]>();
    for (const e of entries) {
      const arr = byFile.get(e.filePath) ?? [];
      arr.push(e);
      byFile.set(e.filePath, arr);
    }
    const sortedFiles = [...byFile.keys()].sort();
    for (const file of sortedFiles) {
      out.push(`### \`${file}\``);
      const recs = byFile
        .get(file)!
        .sort((a, b) => (b.updatedAt > a.updatedAt ? 1 : -1));
      for (const r of recs) {
        out.push(`- ${r.note.replace(/\s+/g, " ").trim()} _(${r.source ?? "?"}${r.severity ? `, ${r.severity}` : ""})_`);
      }
      out.push("");
    }
  } else {
    out.push(
      "_No context captured yet. As you work with AI tools, Kodela records the why " +
        "behind each change and this section fills in automatically._",
      "",
    );
  }

  out.push("---");
  out.push(`_${entries.length} captured change${entries.length === 1 ? "" : "s"} · packed by Kodela._`);

  const content = out.join("\n") + "\n";
  const bytes = Buffer.byteLength(content, "utf8");
  const result: PackResult = {
    content,
    fileCount: files.length,
    entryCount: entries.length,
    bytes,
    tokenEstimate: Math.ceil(content.length / 4),
  };

  if (!opts.stdout) {
    const outPath = path.resolve(repoRoot, opts.out ?? "kodela-pack.md");
    await fs.writeFile(outPath, content, "utf8");
    result.outPath = path.relative(repoRoot, outPath) || (opts.out ?? "kodela-pack.md");
  }
  return result;
}

export function formatPackResult(result: PackResult, output: "text" | "json" = "text"): string {
  if (output === "json") {
    const { content, ...meta } = result;
    return JSON.stringify(meta, null, 2);
  }
  if (!result.outPath) {
    // stdout mode — the content IS the output
    return result.content;
  }
  const kb = (result.bytes / 1024).toFixed(1);
  return [
    `✚ Packed → ${result.outPath}`,
    `  ${result.fileCount} files · ${result.entryCount} captured change${result.entryCount === 1 ? "" : "s"} · ${kb} KB · ~${result.tokenEstimate} tokens`,
    "",
    "Paste it into your LLM, or pipe it: `kodela pack --stdout | pbcopy`.",
  ].join("\n");
}
