// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The Kodela Authors
import { z } from "zod/v4";

export const CiEnforcementSchema = z.enum(["advisory", "enforcement"]);
export type CiEnforcement = z.infer<typeof CiEnforcementSchema>;

export const CiThresholdsSchema = z.object({
  min_confidence_score: z.number().min(0).max(1).default(0.8),
  max_orphaned_pct: z.number().min(0).max(100).default(10),
  max_unresolved_critical_pct: z.number().min(0).max(100).default(5),
});

export type CiThresholds = z.infer<typeof CiThresholdsSchema>;

const DEFAULT_IGNORE_PATTERNS = [
  "node_modules/**",
  ".git/**",
  ".local/**",
  "dist/**",
  "build/**",
  "coverage/**",
  ".cache/**",
  ".next/**",
  ".nuxt/**",
  "*.map",
  "*.js.map",
  "pnpm-lock.yaml",
  "package-lock.json",
  "yarn.lock",
];

const DEFAULT_AI_COMMENT_PATTERNS = [
  "AI-generated",
  "Generated by",
  "Co-authored-by: github-actions",
  "Copilot",
  "ChatGPT",
  "Claude",
  "Gemini",
];

const DEFAULT_SENSITIVE_PATHS = [
  "auth/",
  "authentication/",
  "payments/",
  "billing/",
  "crypto/",
  "cryptography/",
  "security/",
  "secrets/",
  "credentials/",
  "tokens/",
];

export const HealConfigSchema = z.object({
  ai_confidence_cap: z.number().min(0).max(1).default(0.6),
  rewrite_confidence_factor: z.number().min(0).max(1).default(0.85),
});

export type HealConfig = z.infer<typeof HealConfigSchema>;

export const HooksConfigSchema = z.object({
  line_threshold: z.number().int().min(1).default(50),
  minimum_summary_length: z.number().int().min(0).default(10),
  required_fields: z.array(z.string()).default(() => ["note"]),
});

export type HooksConfig = z.infer<typeof HooksConfigSchema>;

/**
 * Hooks-first onboarding (Task #1) — durable, versioned guidance metadata
 * embedded in `kodela.config.json`.
 *
 * The block is optional so older configs continue to parse, and unknown fields
 * are tolerated (via `.passthrough()`) so future CLI versions can extend it
 * without breaking older CLIs.
 *
 * `capture_mode` records which capture path is currently active.  It is updated
 * by `kodela setup`, `kodela hook install --claude`, and `kodela watch --detach`.
 */
export type CaptureMode = "unset" | "hooks" | "watcher" | "manual";

export const KodelaMetadataSchema = z
  .object({
    /**
     * Schema version of the `_kodela` block.  Increment when the shape of
     * the block changes in a breaking way.  Older CLIs that read a newer
     * config emit a warning and refresh-on-write; newer CLIs reading older
     * configs auto-upgrade only on `--force` or `kodela doctor --fix`.
     */
    schema_version: z.number().int().min(0).default(1),
    /** CLI version that last wrote this block (semver string). */
    last_updated_cli_version: z.string().default("0.0.0"),
    /** Currently active capture path. */
    capture_mode: z
      .enum(["unset", "hooks", "watcher", "manual"])
      .default("unset"),
    /** Human-readable next-steps hierarchy (canonical messaging order). */
    next_steps: z.array(z.string()).default(() => []),
    /** Documentation URL for the hooks-first onboarding flow. */
    docs_url: z.string().default("https://kodela.dev/getting-started"),
  })
  .passthrough()
  .optional();

export type KodelaMetadata = z.infer<typeof KodelaMetadataSchema>;

export const KodelaConfigSchema = z.object({
  /**
   * Hooks-first onboarding metadata (Task #1).  Always optional — older
   * configs without this block parse cleanly.
   */
  _kodela: KodelaMetadataSchema,

  heal: HealConfigSchema.default(() => ({
    ai_confidence_cap: 0.6,
    rewrite_confidence_factor: 0.85,
  })),

  hooks: HooksConfigSchema.default(() => ({
    line_threshold: 50,
    minimum_summary_length: 10,
    required_fields: ["note"],
  })),

  ci: z
    .object({
      enforcement: CiEnforcementSchema.default("advisory"),
      thresholds: CiThresholdsSchema.default(() => ({
        min_confidence_score: 0.8,
        max_orphaned_pct: 10,
        max_unresolved_critical_pct: 5,
      })),
    })
    .default(() => ({
      enforcement: "advisory" as const,
      thresholds: {
        min_confidence_score: 0.8,
        max_orphaned_pct: 10,
        max_unresolved_critical_pct: 5,
      },
    })),

  baseline: z
    .object({
      ignore_patterns: z.array(z.string()).default(() => DEFAULT_IGNORE_PATTERNS),
      max_days_before_archive: z.number().int().min(1).default(90),
    })
    .default(() => ({
      ignore_patterns: DEFAULT_IGNORE_PATTERNS,
      max_days_before_archive: 90,
    })),

  ai_detection: z
    .object({
      enabled: z.boolean().default(true),
      min_lines_added: z.number().int().min(1).default(100),
      comment_patterns: z
        .array(z.string())
        .default(() => DEFAULT_AI_COMMENT_PATTERNS),
      insertion_speed_threshold_ms: z
        .number()
        .int()
        .min(0)
        .default(2000),
      editor_insertion_min_lines: z.number().int().min(1).default(10),
      new_file_flag: z.boolean().default(true),
      new_file_min_lines: z.number().int().min(1).default(50),
      /**
       * Gap 23 Option 3 — Human-first bias threshold.
       * When `attributionConfidence` (or UBA score) is below this value,
       * auto-annotate writes `source: "unknown"` / `status: "uncertain"`
       * instead of `source: "ai"` / `status: "mapped"`.
       * Default: 0.7 — protects trust by defaulting to uncertain when unsure.
       * Set to 0 to disable the threshold (not recommended).
       */
      min_auto_annotate_confidence: z.number().min(0).max(1).default(0.7),
    })
    .default(() => ({
      enabled: true,
      min_lines_added: 100,
      comment_patterns: DEFAULT_AI_COMMENT_PATTERNS,
      insertion_speed_threshold_ms: 2000,
      editor_insertion_min_lines: 10,
      new_file_flag: true,
      new_file_min_lines: 50,
      min_auto_annotate_confidence: 0.7,
    })),

  security: z
    .object({
      sensitive_paths: z
        .array(z.string())
        .default(() => DEFAULT_SENSITIVE_PATHS),
    })
    .default(() => ({
      sensitive_paths: DEFAULT_SENSITIVE_PATHS,
    })),

  /**
   * Gap 43 — Push-based alerting when annotations drift.
   * When omitted all notification behaviour is disabled (webhooks default to []).
   */
  notify: z
    .object({
      /**
       * How many hours must elapse before the same entry triggers a second
       * notification for the same drift status.
       * Default: 24 h.  Set to 0 to disable deduplication entirely.
       */
      quiet_hours: z.number().min(0).default(24),
      /**
       * List of webhook endpoints to POST when an annotation drifts during
       * a watch heal cycle or when a snapshot's orphanedPct spikes.
       * Each entry requires a `url`; the optional `secret` is sent as the
       * X-Kodela-Secret header for receiver verification.
       */
      webhooks: z
        .array(
          z.object({
            url: z.string().url(),
            secret: z.string().optional(),
          }),
        )
        .default(() => []),
      /**
       * Orphaned-pct delta (percentage points) that must be exceeded between
       * two consecutive snapshots before a snapshot-level webhook fires.
       * Default: 5.  Only relevant when webhooks are configured.
       */
      webhook_threshold_pct: z.number().min(0).max(100).default(5),
      /**
       * Maps entry author strings to notification routing metadata.
       * The key should match the `author` field on ContextEntry (typically
       * "Name <email>" or a git user name).
       * Example: { "Alice <alice@co.com>": { "slack_user_id": "U0123ABCD" } }
       */
      author_map: z
        .record(
          z.string(),
          z.object({ slack_user_id: z.string().optional() }),
        )
        .default(() => ({})),
    })
    .default(() => ({
      quiet_hours: 24,
      webhooks: [],
      webhook_threshold_pct: 5,
      author_map: {},
    })),

  /**
   * Optional AI provider configuration for `kodela export --ai`.
   * When omitted the AI layer reads from KODELA_AI_PROVIDER / KODELA_AI_API_KEY
   * environment variables. When `--ai` is not used, this block has no effect.
   */
  ai_provider: z
    .object({
      /**
       * Which AI backend to use.
       * Supported values: "openai" (default), "anthropic".
       * Can be overridden by the KODELA_AI_PROVIDER environment variable.
       */
      provider: z.enum(["openai", "anthropic"]).optional(),
      /**
       * Model name to request from the provider.
       * Defaults: openai → "gpt-4o-mini", anthropic → "claude-3-5-haiku-20241022".
       * Can be overridden by the KODELA_AI_MODEL environment variable.
       */
      model: z.string().optional(),
      /**
       * API key for the provider.
       * Prefer using KODELA_AI_API_KEY env var in CI; this field is for
       * local development convenience only — do not commit real keys.
       */
      api_key: z.string().optional(),
      /**
       * Optional base URL override (e.g. for OpenAI-compatible proxies or
       * local models exposing the same HTTP API). Includes scheme and host
       * only — do NOT include a trailing slash.
       * Example: "https://my-litellm-proxy.internal"
       * Can be overridden by the KODELA_AI_BASE_URL environment variable.
       */
      base_url: z.string().optional(),
    })
    .optional(),

  license: z
    .string()
    .optional()
    .describe(
      "Optional path to kodela.license.json. Absolute paths are used as-is; " +
        "relative paths are resolved from the repository root (repoRoot). " +
        "When omitted the license is discovered by walking up the directory tree.",
    ),

  /**
   * Gap 60 — Storage backend configuration.
   * Controls whether annotations are written only to the local `.kodela/`
   * directory ("local") or also queued for async push to a central server
   * ("central").  Defaults to "local" when omitted.
   */
  storage: z
    .object({
      /**
       * Storage mode.
       * "local"   — write only to .kodela/ (default, no network required).
       * "central" — queue-first: write locally then async-push to `server.url`.
       */
      mode: z.enum(["local", "central"]).default("local"),
      /**
       * Remote Kodela server to push annotations to in "central" mode.
       * Must include scheme and host (e.g. "https://kodela.example.com").
       * Ignored in "local" mode.
       */
      server: z
        .object({
          url: z.string().url(),
          api_key_env: z
            .string()
            .default("KODELA_API_KEY")
            .describe(
              "Name of the environment variable that holds the API key. " +
                "Defaults to KODELA_API_KEY.",
            ),
        })
        .optional(),
      /**
       * How often (in seconds) the background flush timer fires to drain the
       * in-memory write queue and push batches to the server.
       * Only relevant in "central" mode.  Defaults to 30 seconds.
       */
      flush_interval_s: z.number().int().min(1).default(30),
      /**
       * Maximum number of annotation entries to hold in the in-memory queue
       * before dropping new ones.  Protects against unbounded memory growth
       * if the server is unreachable for an extended period.
       * Defaults to 500.
       */
      max_queue_size: z.number().int().min(1).default(500),
    })
    .default(() => ({
      mode: "local" as const,
      server: undefined,
      flush_interval_s: 30,
      max_queue_size: 500,
    })),

  /**
   * Gap 58 — AI change spike detection thresholds for `kodela watch` and
   * `kodela detect-ai-change`.  Controls when the watcher prompts the developer
   * (or writes to detection-log.jsonl) about a large, likely-AI change that
   * has no covering ContextEntry.
   */
  detect: z
    .object({
      /**
       * Minimum net lines changed in a single file before the spike detector
       * fires.  Default: 50.
       */
      threshold_lines: z.number().int().min(1).default(50),
      /**
       * Minimum UBA classification score (0–1) to consider a change likely
       * AI-generated.  Default: 0.6 (uncertain zone starts at 0.50 — this
       * threshold sits in the middle to avoid false positives on borderline
       * edits).
       */
      uba_threshold: z.number().min(0).max(1).default(0.6),
      /**
       * When true (default) and the terminal is interactive (TTY), the watcher
       * will prompt the developer to confirm and optionally add a reason.
       * When false or when not a TTY, the detection is written silently to
       * `.kodela/detection-log.jsonl`.
       */
      interactive: z.boolean().default(true),
    })
    .default(() => ({
      threshold_lines: 50,
      uba_threshold: 0.6,
      interactive: true,
    })),

  /**
   * Controls how AI decision context (prompt lineage) is captured.
   * These settings gate what is stored in the `origin` block of ContextEntry.
   */
  origin: z
    .object({
      /**
       * When true, the full prompt text is stored in `origin.prompt`.
       * Disabled by default — privacy-sensitive; do not enable in repositories
       * with sensitive system prompts or proprietary instructions.
       */
      capture_prompt: z.boolean().default(false),
      /**
       * When false, the `origin.reasoning[]` array is omitted from storage
       * even if it is provided by the caller.
       */
      capture_reasoning: z.boolean().default(true),
      /**
       * Hash algorithm used for `origin.promptHash`.
       * "sha256" produces a 64-hex-char hash; "fnv1a" is faster but shorter.
       * SHA-256 is the default (uses Node.js built-in crypto; no extra deps).
       */
      hash_algorithm: z.enum(["sha256", "fnv1a"]).default("sha256"),
    })
    .default(() => ({
      capture_prompt: false,
      capture_reasoning: true,
      hash_algorithm: "sha256" as const,
    })),
}).passthrough();

export type KodelaConfig = z.infer<typeof KodelaConfigSchema>;

/**
 * Gap 43 — Extracted notify block type for use in notify.ts and watch.ts
 * without importing the full KodelaConfig.
 */
export type NotifyConfig = KodelaConfig["notify"];

export const DEFAULT_CONFIG: KodelaConfig = KodelaConfigSchema.parse({});
