// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 The Kodela Authors
import { tryRunGit } from "../utils/exec.js";
import type { KodelaConfig } from "../config/schema.js";

export type NewFileStat = {
  filename: string;
  linesAdded: number;
};

export type CommitAiSignal = {
  commit: string;
  author: string;
  subject: string;
  linesAdded: number;
  linesDeleted: number;
  isLikelyAi: boolean;
  reasons: string[];
  newFiles: NewFileStat[];
};

export type AiDetectionResult = {
  enabled: boolean;
  scanned: number;
  flagged: number;
  signals: CommitAiSignal[];
};

const BUILTIN_AI_SUBJECT_PATTERNS = [
  /\bai[\s-]?generated\b/i,
  /\bcopilot\b/i,
  /\bchatgpt\b/i,
  /\bgpt[-\s]?\d/i,
  /\bclaude\b/i,
  /\bgemini\b/i,
  /\bllm\b/i,
  /^generated by/i,
  /\bai\b.*\bcode\b/i,
];

function buildSubjectPatterns(commentPatterns: string[]): RegExp[] {
  const extra = commentPatterns.map((p) => {
    try {
      return new RegExp(p, "i");
    } catch {
      return new RegExp(p.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
    }
  });
  return [...BUILTIN_AI_SUBJECT_PATTERNS, ...extra];
}

type FileStat = { filename: string; added: number; deleted: number };

/**
 * Parse numstat lines (tab-separated: added\tdeleted\tfilename).
 * Returns per-file breakdowns so callers can cross-reference against
 * the new-file list.
 */
function parseStatLines(stat: string): FileStat[] {
  const files: FileStat[] = [];
  for (const line of stat.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const tabParts = trimmed.split("\t");
    if (tabParts.length >= 3) {
      const added = parseInt(tabParts[0] ?? "0", 10);
      const deleted = parseInt(tabParts[1] ?? "0", 10);
      const filename = tabParts.slice(2).join("\t").trim();
      if (!isNaN(added) && !isNaN(deleted) && filename) {
        files.push({ filename, added, deleted });
      }
    } else {
      const spaceParts = trimmed.split(/\s+/);
      if (spaceParts.length >= 3) {
        const added = parseInt(spaceParts[0] ?? "0", 10);
        const deleted = parseInt(spaceParts[1] ?? "0", 10);
        const filename = spaceParts.slice(2).join(" ").trim();
        if (!isNaN(added) && !isNaN(deleted) && filename) {
          files.push({ filename, added, deleted });
        }
      }
    }
  }
  return files;
}

function sumStat(files: FileStat[]): { added: number; deleted: number } {
  return files.reduce(
    (acc, f) => ({ added: acc.added + f.added, deleted: acc.deleted + f.deleted }),
    { added: 0, deleted: 0 },
  );
}

function looksLikeAiCommit(
  subject: string,
  linesAdded: number,
  minLinesAdded: number,
  patterns: RegExp[],
  newFiles: NewFileStat[],
  newFileMinLines: number,
): { isLikelyAi: boolean; reasons: string[] } {
  const reasons: string[] = [];

  if (linesAdded >= minLinesAdded) {
    reasons.push(
      `large insertion: ${linesAdded} lines added (threshold: ${minLinesAdded})`,
    );
  }

  for (const pattern of patterns) {
    if (pattern.test(subject)) {
      reasons.push(`AI keyword in commit subject: "${subject}"`);
      break;
    }
  }

  const largeNewFiles = newFiles.filter((f) => f.linesAdded >= newFileMinLines);
  if (largeNewFiles.length === 1) {
    reasons.push(
      `new file introduced: ${largeNewFiles[0]!.filename} (${largeNewFiles[0]!.linesAdded} lines)`,
    );
  } else if (largeNewFiles.length > 1) {
    reasons.push(
      `${largeNewFiles.length} new files introduced in a single commit (` +
        largeNewFiles
          .map((f) => `${f.filename}: ${f.linesAdded} lines`)
          .join(", ") +
        ")",
    );
  }

  return {
    isLikelyAi: reasons.length > 0,
    reasons,
  };
}

/**
 * Parse `git log --format=%x1e%H%x00%an%x00%s --numstat` output.
 *
 * Using ASCII record-separator (0x1e) as the commit delimiter ensures each
 * record contains both the commit metadata AND its numstat lines together,
 * avoiding the association bug that occurred with the old \x00\x00 splitter.
 *
 * Record format after splitting by \x1e:
 *   "HASH\x00AUTHOR\x00SUBJECT\nnumstat-line1\nnumstat-line2\n..."
 */
function parseGitLogOutput(
  output: string,
): Array<{ commit: string; author: string; subject: string; stat: string }> {
  if (!output.trim()) return [];

  const RS = "\x1e";
  const records = output.split(RS).filter(Boolean);

  return records
    .map((record) => {
      const newlineIdx = record.indexOf("\n");
      const meta = newlineIdx === -1 ? record : record.slice(0, newlineIdx);
      const stat = newlineIdx === -1 ? "" : record.slice(newlineIdx + 1);
      const parts = meta.split("\x00");
      return {
        commit: parts[0]?.trim() ?? "",
        author: parts[1]?.trim() ?? "",
        subject: parts[2]?.trim() ?? "",
        stat,
      };
    })
    .filter((r) => r.commit.length > 0);
}

/**
 * Parse `git log --diff-filter=A --pretty=format:%H --name-only` output into
 * a map of full commit hash -> list of newly added file paths.
 */
function parseAddedFilesOutput(output: string): Map<string, string[]> {
  const result = new Map<string, string[]>();
  if (!output.trim()) return result;

  let currentHash: string | null = null;
  for (const raw of output.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (/^[0-9a-f]{40}$/i.test(line)) {
      currentHash = line;
      if (!result.has(currentHash)) result.set(currentHash, []);
    } else if (currentHash) {
      result.get(currentHash)!.push(line);
    }
  }
  return result;
}

export async function detectAiCommits(
  repoRoot: string,
  config: KodelaConfig,
  since?: string,
): Promise<AiDetectionResult> {
  if (!config.ai_detection.enabled) {
    return { enabled: false, scanned: 0, flagged: 0, signals: [] };
  }

  const {
    min_lines_added,
    comment_patterns,
    new_file_flag,
    new_file_min_lines,
  } = config.ai_detection;

  const subjectPatterns = buildSubjectPatterns(comment_patterns);
  const rangeArgs = since ? [`--since=${since}`] : ["-50"];

  // %x1e = ASCII record separator — keeps each commit's meta + numstat together
  const gitArgs = [
    "log",
    "--format=%x1e%H%x00%an%x00%s",
    "--numstat",
    ...rangeArgs,
  ];

  const [logResult, addedFilesResult] = await Promise.all([
    tryRunGit(gitArgs, repoRoot),
    new_file_flag
      ? tryRunGit(
          [
            "log",
            "--diff-filter=A",
            "--pretty=format:%H",
            "--name-only",
            ...rangeArgs,
          ],
          repoRoot,
        )
      : Promise.resolve(null),
  ]);

  if (!logResult || !logResult.stdout.trim()) {
    return { enabled: true, scanned: 0, flagged: 0, signals: [] };
  }

  const addedFilesMap = parseAddedFilesOutput(addedFilesResult?.stdout ?? "");
  const records = parseGitLogOutput(logResult.stdout);
  const signals: CommitAiSignal[] = [];

  for (const record of records) {
    const fileStats = parseStatLines(record.stat);
    const { added, deleted } = sumStat(fileStats);

    const addedFilenames = addedFilesMap.get(record.commit) ?? [];
    const newFiles: NewFileStat[] = addedFilenames.map((filename) => {
      const stat = fileStats.find((f) => f.filename === filename);
      return { filename, linesAdded: stat?.added ?? 0 };
    });

    const { isLikelyAi, reasons } = looksLikeAiCommit(
      record.subject,
      added,
      min_lines_added,
      subjectPatterns,
      newFiles,
      new_file_min_lines,
    );

    if (isLikelyAi) {
      signals.push({
        commit: record.commit.slice(0, 8),
        author: record.author,
        subject: record.subject,
        linesAdded: added,
        linesDeleted: deleted,
        isLikelyAi,
        reasons,
        newFiles,
      });
    }
  }

  return {
    enabled: true,
    scanned: records.length,
    flagged: signals.length,
    signals,
  };
}

export function formatAiDetectionResult(
  result: AiDetectionResult,
  outputMode: "text" | "json" = "text",
): string {
  if (outputMode === "json") {
    return JSON.stringify(result, null, 2);
  }

  if (!result.enabled) {
    return "AI detection is disabled. Set ai_detection.enabled: true in kodela.config.json to enable.";
  }

  if (result.scanned === 0) {
    return "No commits found to scan.";
  }

  const lines = [
    `AI commit scan: ${result.flagged} flagged of ${result.scanned} scanned`,
  ];

  if (result.signals.length === 0) {
    lines.push("No likely AI-generated commits detected.");
    return lines.join("\n");
  }

  lines.push("");
  for (const signal of result.signals) {
    lines.push(`  ${signal.commit} ${signal.author}: "${signal.subject}"`);
    for (const reason of signal.reasons) {
      lines.push(`    • ${reason}`);
    }
    if (signal.newFiles.length > 0) {
      lines.push(`    new files:`);
      for (const f of signal.newFiles) {
        lines.push(`      + ${f.filename} (${f.linesAdded} lines)`);
      }
    }
  }

  return lines.join("\n");
}
